import { Injectable, PLATFORM_ID, inject, signal } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

/** Paths tried in order; version.local.txt is gitignored, generated by start-dev.sh. */
export const VERSION_TXT_URLS = ['/version.local.txt', '/version.txt'] as const;

/** Fallback when no version file is readable. */
export const DEFAULT_APP_VERSION = '0.0.0';

export type AppBuildChannel = 'production' | 'staging' | 'development' | 'local';

export interface AppBuildMeta {
  gitHash?: string;
  /** Compact build stamp from version.txt line 4 (YYYYMMDDHHmm). */
  buildStamp?: string;
  channel?: AppBuildChannel;
}

const CHANNEL_UI_LABELS: Record<AppBuildChannel, string> = {
  production: 'production',
  staging: 'staging',
  development: 'développement',
  local: 'local',
};

@Injectable({ providedIn: 'root' })
export class AppVersionService {
  private readonly platformId = inject(PLATFORM_ID);

  readonly version = signal(DEFAULT_APP_VERSION);
  readonly buildMeta = signal<AppBuildMeta | null>(null);

  private loadPromise: Promise<void> | null = null;

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      void this.ensureLoaded();
    }
  }

  /** Resolves when `/version.txt` has been fetched (or failed with fallback). */
  ensureLoaded(): Promise<void> {
    if (!isPlatformBrowser(this.platformId)) {
      return Promise.resolve();
    }
    if (!this.loadPromise) {
      this.loadPromise = this.loadVersion();
    }
    return this.loadPromise;
  }

  private async loadVersion(): Promise<void> {
    try {
      const text = await this.fetchVersionTxt();
      if (!text) {
        return;
      }
      this.version.set(parseVersionTxtFirstLine(text));
      this.buildMeta.set(parseVersionTxtBuildMeta(text));
    } catch {
      /* keep DEFAULT_APP_VERSION */
    }
  }

  private async fetchVersionTxt(): Promise<string | null> {
    for (const url of VERSION_TXT_URLS) {
      try {
        const response = await fetch(url, { cache: 'no-store' });
        if (!response.ok) {
          continue;
        }
        const text = await response.text();
        if (!isVersionTxtResponseUsable(text, url)) {
          continue;
        }
        return text;
      } catch {
        /* try next URL */
      }
    }
    return null;
  }
}

/** Exported for tests — decides whether a fetched version file body should be accepted. */
export function isVersionTxtResponseUsable(text: string, url: string): boolean {
  if (!text.trim()) {
    return false;
  }
  if (url.endsWith('version.local.txt')) {
    const line2 = text.split(/\r?\n/)[1];
    return line2 ? parseBuildChannelFromLine2(line2) !== undefined : false;
  }
  return true;
}

/** Parses the first line of version.txt (exported for tests). */
export function parseVersionTxtFirstLine(text: string): string {
  const firstLine = text.split('\n')[0]?.trim();
  return firstLine || DEFAULT_APP_VERSION;
}

/** Parses deployment channel from version.txt line 2. */
export function parseBuildChannelFromLine2(line: string): AppBuildChannel | undefined {
  const trimmed = line.trim();
  if (trimmed.includes('Production build')) {
    return 'production';
  }
  if (trimmed.includes('Staging RC build')) {
    return 'staging';
  }
  if (trimmed.includes('Development build')) {
    return 'development';
  }
  if (trimmed.includes('Local build')) {
    return 'local';
  }
  return undefined;
}

/** Parses git short hash from version.txt line 3 (`Git: abc1234`). */
export function parseGitHashFromLine3(line: string): string | undefined {
  const match = /^Git:\s*([0-9a-fA-F]+)/.exec(line.trim());
  return match?.[1];
}

/** Parses compact build stamp (YYYYMMDDHHmm) from version.txt line 4. */
export function parseBuildStampFromLine4(line: string): string | undefined {
  const match = /^Build:\s*(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/.exec(line.trim());
  if (!match) {
    return undefined;
  }
  const [, year, month, day, hour, minute] = match;
  return `${year}${month}${day}${hour}${minute}`;
}

/** Parses build metadata from version.txt lines 2–4. */
export function parseVersionTxtBuildMeta(text: string): AppBuildMeta | null {
  const lines = text.split(/\r?\n/);
  const channel = lines[1] ? parseBuildChannelFromLine2(lines[1]) : undefined;
  const gitHash = lines[2] ? parseGitHashFromLine3(lines[2]) : undefined;
  const buildStamp = lines[3] ? parseBuildStampFromLine4(lines[3]) : undefined;
  if (!channel && !gitHash && !buildStamp) {
    return null;
  }
  return {
    ...(channel ? { channel } : {}),
    ...(gitHash ? { gitHash } : {}),
    ...(buildStamp ? { buildStamp } : {}),
  };
}

/** Formats the discrete build meta line for the About screen. */
export function formatBuildMetaLine(meta: AppBuildMeta | null): string | null {
  if (!meta?.channel) {
    return null;
  }
  const label = CHANNEL_UI_LABELS[meta.channel];
  const parts: string[] = [];
  if (meta.gitHash) {
    parts.push(meta.gitHash);
  }
  if (meta.buildStamp) {
    parts.push(meta.buildStamp);
  }
  parts.push(`canal ${label}`);
  return parts.join(' · ');
}
