/** @typedef {'push' | 'email'} NotificationChannel */

/**
 * V2 intent → preference category (mirrors NotificationIntent.kt toCategory).
 * @type {Record<string, string>}
 */
export const INTENT_TO_CATEGORY = {
  AVAILABILITY_OPENED: 'AVAILABILITY_REQUEST',
  MANUAL_AVAILABILITY_ANNOUNCE: 'AVAILABILITY_REQUEST',
  MANUAL_AVAILABILITY_NUDGE: 'AVAILABILITY_REQUEST',
  AVAILABILITY_PENDING_REMINDER: 'AVAILABILITY_WEEKLY_REMINDER',
  COMPOSITION_SHARED: 'ORG_DRAFT_COMPOSITION',
  CONFIRMATION_REQUEST: 'CONFIRMATION_REQUEST',
  TEAM_VALIDATED_FYI: 'TEAM_CONFIRMED',
  ASSIGNEE_PRESENCE_REMINDER_D7: 'REMINDER_7_DAYS',
  ASSIGNEE_PRESENCE_REMINDER_D1: 'REMINDER_1_DAY',
  REMOVED_FROM_COMPOSITION: 'CONFIRMATION_REQUEST',
  RECONFIRMATION_REQUEST: 'CONFIRMATION_REQUEST',
  PROXY_AVAILABILITY_RECORDED: 'AVAILABILITY_REQUEST',
  PROXY_CONFIRMATION_RECORDED: 'CONFIRMATION_REQUEST',
  EVENT_DETAILS_CHANGED: 'EVENT_DETAILS_CHANGED',
  EVENT_ARCHIVED: 'EVENT_ARCHIVED',
  TEAM_COMPLETE_MEMBER: 'TEAM_CONFIRMED',
  EVENT_DRAFT_CREATED: 'ORG_EVENT_DRAFT_CREATED',
  SLA_OPEN_AVAILABILITY: 'ORG_SLA_OPEN_AVAILABILITY',
  COMPOSITION_INCOMPLETE_WEEKLY: 'ORG_COMPOSITION_INCOMPLETE',
  COMPOSITION_INCOMPLETE_DAILY_J7: 'ORG_COMPOSITION_INCOMPLETE',
  TEAM_COMPLETE: 'ORG_TEAM_COMPLETE',
  TEAM_REGRESSED: 'ORG_TEAM_REGRESSED',
  ORGANIZER_SCOPE_GRANTED: 'ORG_SCOPE_GRANTED',
}

/** Categories in ORGANIZER_ALERTS group (opt-in OFF/OFF by default). */
export const ORGANIZER_CATEGORY_PREFIX = 'ORG_'

/**
 * @param {string} category
 * @returns {'participant' | 'organizer'}
 */
export function audienceRoleForCategory(category) {
  return category.startsWith(ORGANIZER_CATEGORY_PREFIX) ? 'organizer' : 'participant'
}
