name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to Firebase Production
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HATCAST }}'
        channelId: live
        projectId: impro-selector
        entryPoint: ./
        target: production
        
    - name: Deploy Firebase Functions
      run: |
        npm install -g firebase-tools
        firebase deploy --only functions --project impro-selector --token "${{ secrets.FIREBASE_TOKEN }}"
        
    - name: Deploy Firestore Rules
      run: |
        firebase deploy --only firestore:rules --project impro-selector --token "${{ secrets.FIREBASE_TOKEN }}"
        
    - name: Deploy Storage Rules
      run: |
        firebase deploy --only storage --project impro-selector --token "${{ secrets.FIREBASE_TOKEN }}"
        
    - name: Notify deployment success
      run: |
        echo "🚀 Déploiement PRODUCTION réussi !"
        echo "🌐 URL: https://votre-projet-production.web.app"
        echo "📧 Emails envoyés via Gmail"
        echo ""
        echo "⚠️  ATTENTION: Application déployée en PRODUCTION"
        echo "   Vérifiez que tout fonctionne correctement !"
